name: Python Security Operations

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace 'x' with the appropriate version of Python you want to use

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Install pytest

    - name: Run Tests
      run: pytest

    - name: Code Scanning
      uses: github/codeql-action/init@v2
